# Numpy (Numerical Python) (Python untuk perhitungan numerik)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # matriks

In [3]:
a * 3

array([3, 6, 9])

# Math Function

In [4]:
np.sum(a) # jumlah yang ada pada matriks

6

In [5]:
np.mean(a) # rata2 matriks

2.0

In [6]:
np.std(a) # standar deviasi

0.816496580927726

In [7]:
np.sin(a) # fungsi trigonometri

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [8]:
np.arange(0, 5) # range dalam bentuk matriks np.arange(awal, batas akhir, interval)

array([0, 1, 2, 3, 4])

In [9]:
np.linspace(0, 10, 3) # range dari 1 sampai 10 dipecah menjadi 3 unit

array([ 0.,  5., 10.])

In [10]:
np.logspace(3, 5, 2)

array([  1000., 100000.])

# Random

In [11]:
np.random.rand()

0.9306471710831131

In [12]:
np.random.rand(3)

array([0.92697157, 0.793804  , 0.22940189])

In [13]:
np.random.rand(3,2)

array([[0.99714156, 0.66524772],
       [0.13459703, 0.14695985],
       [0.61959871, 0.22111548]])

# Controlled Randomness (Pengacakan yang diatur)

In [14]:
state = np.random.RandomState(42) # 42 itu parameter, selama parameternya sama, maka randomnya akan sama
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])